name: Build browsh
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Pre-build
        run: ./interfacer/contrib/build_browsh.sh
      - name: Build
        working-directory: ./interfacer
        run: go build ./cmd/browsh
      - name: Test
        run: ./interfacer/browsh --version

