name: Run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: ./webext
      - run: npm test
        working-directory: ./webext
      - uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      - run: npm install
        working-directory: ./webext
      - run: npx webpack
        working-directory: ./webext
      - name: Pre-build
        run: ./interfacer/contrib/build_browsh.sh
      - name: Build
        working-directory: ./interfacer
        run: go build ./cmd/browsh
      - run: go test -v ./...
        working-directory: ./interfacer
      - name: Test
        run: ./interfacer/browsh --version

