name: Run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install latest Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 102.0.1 # TODO: Use same version in Dockerfile
      - run: firefox --version

      # Web extension tests
      # TODO: can these all be shared in a single script?
      - run: npm ci
        working-directory: ./webext
      - name: Web extension tests
        run: npm test
        working-directory: ./webext
      - run: npm install
        working-directory: ./webext
      - run: npx webpack
        working-directory: ./webext

      # Interfacer tests
      - name: Pre-build
        run: ./interfacer/contrib/build_browsh.sh
      - name: Build # TODO: should this be included in `build_browsh.sh`?
        working-directory: ./interfacer
        run: go build ./cmd/browsh

      - name: Unit tests
        run: go test -v $(find src/browsh -name '*.go' | grep -v windows)
        working-directory: ./interfacer
      - name: TTY tests
        run: go test test/tty/*.go -v -ginkgo.slowSpecThreshold=30 -ginkgo.flakeAttempts=3
        working-directory: ./interfacer
      - name: TTY debug log
        if: ${{ failure() }}
        run: cat ./interfacer/test/tty/debug.log
      - name: HTTP Server tests
        run: go test test/http-server/*.go -v -ginkgo.slowSpecThreshold=30 -ginkgo.flakeAttempts=3
        working-directory: ./interfacer
      - name: HTTP Server debug log
        if: ${{ failure() }}
        run: cat ./interfacer/test/http-server/debug.log

